function(print_variables)
    message(STATUS "The CMake SOURCE directory is ${CMAKE_CURRENT_LIST_FILE}")
    message(STATUS "The CMake SOURCE directory is ${CMAKE_SOURCE_DIR}")
    message(STATUS "The CMake BINARY directory is ${CMAKE_BINARY_DIR}")
endfunction()