name: Trigger Jenkins Job

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  statuses: write

jobs:
  trigger-jenkins-job:
    runs-on: runner
    
    if: github.base_ref != 'main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Branch Name
        run: | 
         echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
         echo "GitHub Ref: ${{ github.base_ref }}"
         echo "GitHub Ref: ${{ github.ref }}"
         
      - name: Debug Environment Variables
        if: github.base_ref == 'main'
        run: |
          export JENKINS_USER="${{ secrets.JENKINS_USER }}"
          export JENKINS_TOKEN="${{ secrets.JENKINS_TOKEN }}"
          source .github/workflows/UTILS/utils.sh
           
      - name: Multibranch Pipeline Trigger
        if: github.base_ref != 'main'
        run: | 
         echo "URL: $URL"
         echo "AUTH: $AUTH"
         echo "CURL: $CURL"
         echo "CURL_POST: $CURL_POST"

         trigger=$(${{ env.CURL_POST }} "${{ env.URL }}/job/matt-wash-projects/job/${{ env.BRANCH_NAME }}/build")

      - name: test get
        if: github.base_ref != 'main'
        run: | 
          trigger_unquoted=$(${{ env.CURL }} "${{ env.URL }}/job/matt-wash-projects/job/${{ env.BRANCH_NAME }}/lastBuild/api/json?tree=result")
          res=$(echo -n "$trigger_unquoted" | jq -r '.result')
          echo $trigger_unquoted
          echo "$res"
 
      - name: access variable from utils.sh
        if: github.base_ref != 'main'
        run: | 
         echo $URL
         echo "$POST"
         echo "$POST"
         echo $AUTH

      - name: Set PR Status
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # trying to run tests to edit status of pr
          
          if [ $GITHUB_BASE_REF == "main" ]; then
            STATE="error"
          else
            STATE="failure"
          fi

          # Set the PR status using GitHub API
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -d '{"state": "'$STATE'", "context": "Trigger Jenkins Job"}'
