name: Trigger Jenkins Job

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - any

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  statuses: write

jobs:
  trigger-jenkins-job:
    runs-on: runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Branch Name
        run: | 
         echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
           
      - name: Multibranch Pipeline Trigger
        run: |
         source .github/workflows/UTILS/utils.sh 
         echo $URL
         echo "$POST"
         echo "$POST"
         echo $AUTH
         trigger=($CURL_POST "$URL/job/matt-wash-projects/job/${{ env.BRANCH_NAME }}/build")

      - name: access variable from utils.sh
        run: | 
         echo $URL
         echo "$POST"
         echo "$POST"
         echo $AUTH
