name: Determine Base Branch

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  determine-base-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display base branch
      run: echo "Base branch is $GITHUB_BASE_REF"
