name: Determine Base Branch

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  determine-base-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3

    - name: test sleep
      run: |
        build_status="false"

          while [ "build_status" == "false" ]; then
            sleep 1
            echo "sleeping"
            sleep 1
            echo "sleeping"
            sleep 1
            echo "sleeping"
            sleep 1
            echo "sleeping"
            build_status="true"
          done

    - name: Display base branch
      run: echo "Base branch is $GITHUB_BASE_REF"
