name: CPPCheck Ubuntu

on: 
  workflow_dispatch:
  pull_request:
    types: [opened, syncronized, reopened]

jobs:
  cppcheck:
    runs-on: runner
    container:
      image: ubuntu:24.04
      env: 
        CONTAINER_NAME: Ubuntu_CPPCheck

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install cppcheck
      run: |
        apt-get update
        apt-get install -y cppcheck

    - name: Get Container ID
      run: |
        echo "Container ID: "
        cat /etc/hostname


  
