name: keep-alive

on:
  workflow_dispatch:

permissions:
  issues: write

jobs: 
  keep-alive:
    runs-on: developer-builds

    steps:
      - name: simulate-failure
        run: exit 1

      - name: create issue
        if: ${{ failure() }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title": "'"${{ github.workflow }}"': workflow error", "body": "An error occurred when running '"${{ github.workflow }}"' further investigation required. cc @mysticrecords", "labels": ["github-actions"]}'
