name: test-queuing-jobs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  build:
    name: queuing
    runs-on: developer-builds
    steps:

      - name: sleep
        id: sleep
        run: |
          sleep 5
          echo "job complete"

      - name: set test status
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}/job/${{ github.run_id }}#step:1:1" \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -d '{"state": "${{ steps.sleep.outcome }}", "context": "Sleep Status"}'
